
import { Button, HorizontalBox, VerticalBox, GridBox, TabWidget, ComboBox  } from "std-widgets.slint";
import { ControlViewPort } from "../ui/control.slint";

export global Cam {
    pure callback render-image(int) -> image;
    in-out property<int> frame;
}

export component CameraViewport {
    pure callback render-image(int) -> image;
    in-out property<int> frame;

         Rectangle { background: white; min-width: 16px; min-height: 16px;padding: 5px;
                VerticalLayout {alignment: center; width: 100%;height: 100%;
                    CameraBox := Rectangle { width: 640px;height: 480px;
                        Image { padding: 5px;width: 100%; height: 100%; source: render-image(frame);}
                    }
                    CameraSwitch := Rectangle { width: 640px;
                       HorizontalLayout {
                            ComboBox {
                                padding-left: 5px;
                                width: self.preferred-width * 2;
                                //height: self.preferred-height *2 ;
                                model: ["Camera 1", "Camera 2", "Camera 3"];
                                current-value: "Camera 1";
                            }
                            Button { visible: false; text: "Calibrate"; }
                            btnCamPwr := Button { padding: 10px; height: 40px; width: 100px; text: "Turn On/Off";  }
                            Button { visible: false; text: "Calibrate"; }
                            btnCalibrate := Button { padding: 10px; height: 40px; width: 100px; text: "Calibrate";  }
                            Button { visible: false; text: "Calibrate"; }
                       }
                    }
                }
         }
}
